version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: collaborative-learning-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: collaborative_learning_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Optional: Database management tool
  adminer:
    image: adminer:latest
    container_name: collaborative-learning-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
